source "https://rubygems.org"
ruby "2.3.1"

gem "lita"
gem "lita-slack"
gem "lita-karma"
gem "lita-slack-karma-sync"
gem "lita-ignore-me"
gem "lita-imgflip"
gem "lita-poll"
gem "lita-replace"
gem "lita-static-meme"
gem "lita-tinysong"
